export const renderCodeList = (data: string, codeName: string) => {
  if (!codeList[codeName]) {
    return ''
  }
  return codeList[codeName][data];
}

export const localizeCodeList = (t) => {
  for (const codeListKey in codeList) {
    for (const key in codeList[codeListKey]) {
      const code = codeList[codeListKey][key]
      code.label = t(code.i18nKey)
      console.debug(code.value + "=" + code.label)
    }
  }
}

export const codeList = {

  ReportAlignment: [{value: "", label: "请选择", i18nKey: "code_list.common.empty"},

    {value: "left", label: "居左", i18nKey: "code_list.ReportAlignment.left"},
    {value: "center", label: "居中", i18nKey: "code_list.ReportAlignment.center"},
    {value: "right", label: "居右", i18nKey: "code_list.ReportAlignment.right"},
  ],
  PageAlignment: [{value: "", label: "请选择", i18nKey: "code_list.common.empty"},
    {value: "left", label: "居左", i18nKey: "code_list.PageAlignment.left"},
    {value: "center", label: "居中", i18nKey: "code_list.PageAlignment.center"},
    {value: "right", label: "居右", i18nKey: "code_list.PageAlignment.right"},
  ],
  ReportLayoutSectionType: [{value: "", label: "请选择", i18nKey: "code_list.common.empty"},
    {value: "header", label: "表头", i18nKey: "code_list.ReportLayoutSectionType.header"},
    {value: "detail", label: "详细数据", i18nKey: "code_list.ReportLayoutSectionType.detail"},
    {value: "summary", label: "合计", i18nKey: "code_list.ReportLayoutSectionType.summary"},
  ],
  ApiType: [{value: "", label: "请选择", i18nKey: "code_list.common.empty"},
    {value: "soap", label: "SOAP", i18nKey: "code_list.ApiType.soap"},
    {value: "http", label: "HTTP", i18nKey: "code_list.ApiType.http"},
  ],
  InternalApiType: [{value: "", label: "请选择", i18nKey: "code_list.common.empty"},
    {value: "table_data_page", label: "返回数据库表分页", i18nKey: "code_list.InternalApiType.table_data_page"},
    {value: "table_data_list", label: "返回数据库表全部", i18nKey: "code_list.InternalApiType.table_data_list"},
    {value: "table_data_create", label: "创建数据库表数据", i18nKey: "code_list.InternalApiType.table_data_create"},
    {value: "table_data_update", label: "保存数据库表数据", i18nKey: "code_list.InternalApiType.table_data_update"},
    {value: "table_data_delete", label: "删除数据库表数据", i18nKey: "code_list.InternalApiType.table_data_delete"},
    {value: "table_data_get", label: "返回数据库表单条数据", i18nKey: "code_list.InternalApiType.table_data_get"},
    {value: "get_summary_data", label: "返回汇总数据", i18nKey: "code_list.InternalApiType.get_summary_data"},

  ],
  PageType: [{value: "", label: "请选择", i18nKey: "code_list.common.empty"},
    {value: "main_page", label: "主页面", i18nKey: "code_list.PageType.main_page"},
    {value: "child_page", label: "子页面", i18nKey: "code_list.PageType.child_page"},
    {value: "modal", label: "弹出框", i18nKey: "code_list.PageType.modal"},
    {value: "component", label: "组件", i18nKey: "code_list.PageType.component"},
    {value: "dashboard", label: "数据大屏", i18nKey: "code_list.PageType.dashboard"},
  ],
  ParamFieldType: [{value: "", label: "请选择", i18nKey: "code_list.common.empty"},
    {value: "object", label: "容器", i18nKey: "code_list.ParamFieldType.object"},
    {value: "text", label: "文字", i18nKey: "code_list.ParamFieldType.text"},
    {value: "number", label: "数字", i18nKey: "code_list.ParamFieldType.number"},
    {value: "datetime", label: "日期时间", i18nKey: "code_list.ParamFieldType.datetime"},
    {value: "boolean", label: "布尔(是/否)", i18nKey: "code_list.ParamFieldType.boolean"},
  ],
  ParamFieldSource: [{value: "", label: "请选择", i18nKey: "code_list.common.empty"},
    {value: "global", label: "全局", i18nKey: "code_list.ParamFieldSource.global"},
    {value: "parent", label: "上级组件", i18nKey: "code_list.ParamFieldSource.parent"},
  ],
  ExtractResultType: [{value: "", label: "请选择", i18nKey: "code_list.common.empty"},
    {value: "page_description", label: "页面说明", i18nKey: "code_list.ExtractResultType.page_description"},
    {value: "api_description", label: "接口说明", i18nKey: "code_list.ExtractResultType.api_description"},
    {value: "biz_flow_description", label: "业务流程说明", i18nKey: "code_list.ExtractResultType.biz_flow_description"},
    {value: "page_flow_description", label: "页面流说明", i18nKey: "code_list.ExtractResultType.page_flow_description"},
    {value: "api_input_fields", label: "接口入参字段定义", i18nKey: "code_list.ExtractResultType.api_input_fields"},
    {value: "update_api", label: "接口出参字段定义", i18nKey: "code_list.ExtractResultType.update_api"},
    {value: "page_search_fields", label: "页面查询条件字段", i18nKey: "code_list.ExtractResultType.page_search_fields"},
    {
      value: "search_result_fields",
      label: "页面查询结果字段",
      i18nKey: "code_list.ExtractResultType.search_result_fields"
    },
  ],
  SourceType: [{value: "", label: "请选择", i18nKey: "code_list.common.empty"},
    {value: "picture", label: "图片", i18nKey: "code_list.SourceType.picture"},
    {value: "html", label: "HTML", i18nKey: "code_list.SourceType.html"},
    {value: "ai-extract", label: "AI提取", i18nKey: "code_list.SourceType.ai-extract"},
    {value: "manual", label: "图片", i18nKey: "code_list.SourceType.manual"},
    {value: "page", label: "图片", i18nKey: "code_list.SourceType.page"},
    {value: "pageSection", label: "图片", i18nKey: "code_list.SourceType.pageSection"},
  ],
  ConceptualType: [{value: "", label: "请选择", i18nKey: "code_list.common.empty"},
    {value: "text", label: "文字", i18nKey: "code_list.ConceptualType.text"},
    {value: "number", label: "数字", i18nKey: "code_list.ConceptualType.number"},
    {value: "datetime", label: "日期时间", i18nKey: "code_list.ConceptualType.datetime"},
    {value: "boolean", label: "布尔(是/否)", i18nKey: "code_list.ConceptualType.boolean"},
    {value: "enum", label: "枚举", i18nKey: "code_list.ConceptualType.enum"},
  ],
  LogicalType: [{value: "", label: "请选择", i18nKey: "code_list.common.empty"},
    {value: "string", label: "短文字", i18nKey: "code_list.LogicalType.string"},
    {value: "text", label: "长文字", i18nKey: "code_list.LogicalType.text"},
    {value: "integer", label: "整数", i18nKey: "code_list.LogicalType.integer"},
    {value: "float", label: "浮点数", i18nKey: "code_list.LogicalType.float"},
    {value: "date", label: "日期", i18nKey: "code_list.LogicalType.date"},
    {value: "time", label: "时间", i18nKey: "code_list.LogicalType.time"},
    {value: "datetime", label: "日期时间", i18nKey: "code_list.LogicalType.datetime"},
    {value: "boolean", label: "布尔(是/否)", i18nKey: "code_list.LogicalType.boolean"},
    {value: "enum", label: "枚举", i18nKey: "code_list.LogicalType.enum"},
  ],
  DataPhase: [{value: "", label: "请选择", i18nKey: "code_list.common.empty"},
    {value: "conceptual", label: "概念模型", i18nKey: "code_list.DataPhase.conceptual"},
    {value: "logical", label: "逻辑模型", i18nKey: "code_list.DataPhase.logical"},
    {value: "physical", label: "物理模型", i18nKey: "code_list.DataPhase.physical"},
  ],
  PhysicalType: [{value: "", label: "请选择", i18nKey: "code_list.common.empty"},
    {value: "char", label: "固定长字符串", i18nKey: "code_list.PhysicalType.char"},
    {value: "varchar", label: "可变长字符串", i18nKey: "code_list.PhysicalType.varchar"},
    {value: "text", label: "长文本", i18nKey: "code_list.PhysicalType.text"},
    {value: "short", label: "短整数", i18nKey: "code_list.PhysicalType.short"},
    {value: "int", label: "整数", i18nKey: "code_list.PhysicalType.int"},
    {value: "long", label: "长整数", i18nKey: "code_list.PhysicalType.long"},
    {value: "float", label: "单精度浮点数", i18nKey: "code_list.PhysicalType.float"},
    {value: "double", label: "双精度浮点数", i18nKey: "code_list.PhysicalType.double"},
    {value: "date", label: "日期时间", i18nKey: "code_list.PhysicalType.date"},
    {value: "time", label: "日期时间", i18nKey: "code_list.PhysicalType.time"},
    {value: "datetime", label: "日期时间", i18nKey: "code_list.PhysicalType.datetime"},
    {value: "boolean", label: "布尔(是/否)", i18nKey: "code_list.PhysicalType.boolean"},
    {value: "enum", label: "枚举", i18nKey: "code_list.PhysicalType.enum"},
  ],
  FieldFormat: [{value: "", label: "请选择", i18nKey: "code_list.common.empty"},
    {value: "float1", label: "一位小数", i18nKey: "code_list.FieldFormat.float1"},
    {value: "float2", label: "两位小数", i18nKey: "code_list.FieldFormat.float2"},
    {value: "integer", label: "整数", i18nKey: "code_list.FieldFormat.integer"},
    {value: "yyyy-MM-dd hh:mm:ss", label: "年月日时分秒", i18nKey: "code_list.FieldFormat.yyyy-MM-dd_hhmmss"},
    {value: "yyyy-MM-dd hh:mm", label: "年月日时分", i18nKey: "code_list.FieldFormat.yyyy-MM-dd_hhmm"},
    {value: "yyyy-MM-dd hh", label: "年月日时", i18nKey: "code_list.FieldFormat.yyyy-MM-dd_hh"},
    {value: "hh:mm:ss", label: "时分秒", i18nKey: "code_list.FieldFormat.hhmmss"},
    {value: "hh:mm", label: "时分", i18nKey: "code_list.FieldFormat.hhmm"},
    {value: "hh", label: "小时", i18nKey: "code_list.FieldFormat.hh"},
    {value: "integer_by_thousand", label: "千分整数", i18nKey: "code_list.FieldFormat.integer_by_thousand"},
    {value: "integer_by_10thousand", label: "万分整数", i18nKey: "code_list.FieldFormat.integer_by_10thousand"},
  ],
  DevPhase: [{value: "", label: "请选择", i18nKey: "code_list.common.empty"},
    {value: "demand", label: "需求分析", i18nKey: "code_list.DevPhase.demand"},
    {value: "basic", label: "概要设计", i18nKey: "code_list.DevPhase.basic"},
    {value: "detail", label: "详细设计", i18nKey: "code_list.DevPhase.detail"},
    {value: "make", label: "开发", i18nKey: "code_list.DevPhase.make"},
    {value: "test", label: "测试", i18nKey: "code_list.DevPhase.test"},
  ],
  ConnectType: [{value: "", label: "请选择", i18nKey: "code_list.common.empty"},
    {value: "soap", label: "SOAP", i18nKey: "code_list.ConnectType.soap"},
    {value: "http", label: "HTTP API", i18nKey: "code_list.ConnectType.http"},
  ],
  HttpProtocol: [{value: "", label: "请选择", i18nKey: "code_list.common.empty"},
    {value: "http", label: "HTTP", i18nKey: "code_list.HttpProtocol.http"},
    {value: "https", label: "HTTPS", i18nKey: "code_list.HttpProtocol.https"},
  ],
  HttpMethod: [{value: "", label: "请选择", i18nKey: "code_list.common.empty"},
    {value: "get", label: "GET", i18nKey: "code_list.HttpMethod.get"},
    {value: "post", label: "POST", i18nKey: "code_list.HttpMethod.post"},
    {value: "put", label: "PUT", i18nKey: "code_list.HttpMethod.put"},
    {value: "delete", label: "DELETE", i18nKey: "code_list.HttpMethod.delete"},
  ],
  AuthMethod: [{value: "", label: "请选择", i18nKey: "code_list.common.empty"},
    {value: "none", label: "None", i18nKey: "code_list.AuthMethod.none"},
    {value: "token", label: "Token", i18nKey: "code_list.AuthMethod.token"},
  ],
  TokenParamType: [{value: "", label: "请选择", i18nKey: "code_list.common.empty"},
    {value: "header", label: "Header", i18nKey: "code_list.TokenParamType.header"},
    {value: "body", label: "Body", i18nKey: "code_list.TokenParamType.body"},
  ],
  RequestType: [{value: "", label: "请选择", i18nKey: "code_list.common.empty"},
    {value: "form", label: "FORM", i18nKey: "code_list.RequestType.form"},
    {value: "json", label: "JSON", i18nKey: "code_list.RequestType.json"},
    {value: "url_param", label: "URL PARAM", i18nKey: "code_list.RequestType.url_param"},
  ],
  ExternalApiType: [{value: "", label: "请选择", i18nKey: "code_list.common.empty"},
    {value: "soap", label: "SOAP", i18nKey: "code_list.ExternalApiType.soap"},
    {value: "http", label: "HTTP", i18nKey: "code_list.ExternalApiType.http"},
  ],
  IndicatorShowType: [{value: "", label: "请选择", i18nKey: "code_list.common.empty"},
    {value: "table", label: "数据表", i18nKey: "code_list.IndicatorShowType.table"},
    {value: "chart", label: "图形", i18nKey: "code_list.IndicatorShowType.chart"},
  ],
  ApiResultType: [
    {value: "object", label: "数据对象容器", i18nKey: "code_list.ApiResultType.object"},
    {value: "list", label: "数据列表", i18nKey: "code_list.ApiResultType.list"},
    {value: "page", label: "数据分页", i18nKey: "code_list.ApiResultType.page"},
    {value: "value", label: "单值", i18nKey: "code_list.ApiResultType.value"},
  ],
  IndicatorChartType: [{value: "", label: "请选择", i18nKey: "code_list.common.empty"},
    {value: "pie", label: "饼状图", i18nKey: "code_list.IndicatorChartType.pie"},
    {value: "line", label: "折线图", i18nKey: "code_list.IndicatorChartType.line"},
    {value: "bar", label: "柱状图", i18nKey: "code_list.IndicatorChartType.bar"},
  ],
  TestPhase: [{value: "", label: "请选择", i18nKey: "code_list.common.empty"},
    {value: "ut", label: "开发测试用", i18nKey: "code_list.TestPhase.ut"},
    {value: "st", label: "结合测试用", i18nKey: "code_list.TestPhase.st"},
    {value: "rt", label: "交付验收用", i18nKey: "code_list.TestPhase.rt"},
  ],
  TestTargetType: [{value: "", label: "请选择", i18nKey: "code_list.common.empty"},
    {value: "page", label: "页面", i18nKey: "code_list.TestTargetType.page"},
    {value: "external_api", label: "外部接口", i18nKey: "code_list.TestTargetType.external_api"},
    {value: "internal_api", label: "内部接口", i18nKey: "code_list.TestTargetType.internal_api"},
    {value: "report", label: "报表", i18nKey: "code_list.TestTargetType.report"},
    {value: "report_indicator", label: "报表指标", i18nKey: "code_list.TestTargetType.report_indicator"},
    {value: "groovy_script", label: "Groovy脚本", i18nKey: "code_list.TestTargetType.groovy_script"},
    {value: "js_script", label: "Javascript脚本", i18nKey: "code_list.TestTargetType.js_script"},
    {value: "cron_task", label: "定时任务", i18nKey: "code_list.TestTargetType.cron_task"},
    {value: "notification", label: "系统通知", i18nKey: "code_list.TestTargetType.notification"},
    {value: "sql", label: "SQL", i18nKey: "code_list.TestTargetType.sql"},
  ],
  TestTargetSubType1: [{value: "", label: "请选择", i18nKey: "code_list.common.empty"},
    {value: "page-init", label: "页面-初始化", i18nKey: "code_list.TestTargetSubType1.page-init"},
  ],
  TestTargetSubType2: [{value: "", label: "请选择", i18nKey: "code_list.common.empty"},
    {value: "page-init", label: "页面-初始化", i18nKey: "code_list.TestTargetSubType2.page-init"},
  ],
  PageScopeType: [{value: "", label: "请选择", i18nKey: "code_list.common.empty"},
    {value: "global", label: "全局", i18nKey: "code_list.PageScopeType.global"},
    {value: "module", label: "模块", i18nKey: "code_list.PageScopeType.module"},
    {value: "function", label: "功能", i18nKey: "code_list.PageScopeType.function"},
  ],
  YesNo: [{value: '', label: '请选择', i18nKey: 'code_list.common.empty'},
    {value: '1', label: '是', i18nKey: 'code_list.YesNo.yes'},
    {value: '0', label: '否', i18nKey: 'code_list.YesNo.no'},
  ],
  PageVarScopeType: [{value: "", label: "请选择", i18nKey: "code_list.common.empty"},
    {value: "global", label: "全局", i18nKey: "code_list.PageScopeType.global"},
    {value: "module", label: "模块", i18nKey: "code_list.PageScopeType.module"},
    {value: "function", label: "功能", i18nKey: "code_list.PageScopeType.function"},
    {value: "page", label: "页面", i18nKey: "code_list.PageScopeType.page"},
    {value: "page_layout", label: "页面布局", i18nKey: "code_list.PageScopeType.page_layout"},
  ],
  PageEventType: [{value: "", label: "请选择", i18nKey: "code_list.common.empty"},
    {value: "open", label: "打开", i18nKey: "code_list.PageEventType.open"},
    {value: "load", label: "开始加载", i18nKey: "code_list.PageEventType.load"},
    {value: "loaded", label: "加载完成", i18nKey: "code_list.PageEventType.loaded"},
    {value: "close", label: "关闭", i18nKey: "code_list.PageEventType.close"},
  ],
  PageFieldEventType: [{value: "", label: "请选择", i18nKey: "code_list.common.empty"},
    {value: "enter", label: "进入", i18nKey: "code_list.PageFieldEventType.enter"},
    {value: "load", label: "开始加载", i18nKey: "code_list.PageFieldEventType.load"},
    {value: "loaded", label: "加载完成", i18nKey: "code_list.PageFieldEventType.loaded"},
    {value: "blur", label: "失去焦点", i18nKey: "code_list.PageFieldEventType.blur"},
    {value: "click", label: "点击", i18nKey: "code_list.PageFieldEventType.click"},
    {value: "dbClick", label: "双击", i18nKey: "code_list.PageFieldEventType.dbClick"},
    {value: "changed", label: "变化", i18nKey: "code_list.PageFieldEventType.changed"},
  ],
  TransitionType: [{value: "", label: "请选择", i18nKey: "code_list.common.empty"},
    {value: "page_transition", label: "页面跳转", i18nKey: "code_list.TransitionType.page_transition"},
    {value: "show_modal", label: "弹出窗口", i18nKey: "code_list.TransitionType.show_modal"},
    {value: "show_layer", label: "显示隐藏层", i18nKey: "code_list.TransitionType.show_layer"},
  ],
  ComponentType: [{value: "", label: "请选择", i18nKey: "code_list.common.empty"},
    {value: "fieldSet", label: "字段组", i18nKey: "code_list.ComponentType.fieldSet"},
    {value: "label", label: "静态文本标签", i18nKey: "code_list.ComponentType.label"},
    {value: "data", label: "动态数据显示", i18nKey: "code_list.ComponentType.data"},
    {value: "text", label: "文本输入框", i18nKey: "code_list.ComponentType.text"},
    {value: "textarea", label: "多行文本输入框", i18nKey: "code_list.ComponentType.textarea"},
    {value: "number", label: "整数输入框", i18nKey: "code_list.ComponentType.number"},
    {value: "float", label: "小数输入框", i18nKey: "code_list.ComponentType.float"},
    {value: "select", label: "选择框", i18nKey: "code_list.ComponentType.select"},
    {value: "multiselect", label: "多值选择框", i18nKey: "code_list.ComponentType.multiselect"},
    {value: "switch", label: "开关", i18nKey: "code_list.ComponentType.switch"},
    {value: "checkbox", label: "复选框", i18nKey: "code_list.ComponentType.checkbox"},
    {value: "radio", label: "单选框", i18nKey: "code_list.ComponentType.radio"},
    {value: "date", label: "日期", i18nKey: "code_list.ComponentType.date"},
    {value: "time", label: "时间", i18nKey: "code_list.ComponentType.time"},
    {value: "datetime", label: "日期时间", i18nKey: "code_list.ComponentType.datetime"},
    {value: "daterange", label: "日期范围", i18nKey: "code_list.ComponentType.daterange"},
    {value: "timerange", label: "时间范围", i18nKey: "code_list.ComponentType.timerange"},
    {value: "datetimerange", label: "日期时间范围", i18nKey: "code_list.ComponentType.datetimerange"},
    {value: "file", label: "文件上传", i18nKey: "code_list.ComponentType.file"},
    {value: "picture", label: "图片上传", i18nKey: "code_list.ComponentType.picture"},
    {value: "richedit", label: "富文本编辑框", i18nKey: "code_list.ComponentType.richedit"},
    {value: "jsonedit", label: "JSON编辑框", i18nKey: "code_list.ComponentType.jsonedit"},
    {value: "codeedit", label: "源码编辑框", i18nKey: "code_list.ComponentType.codeedit"},
    {value: "button", label: "按钮", i18nKey: "code_list.ComponentType.button"},
    {value: "table", label: "表格", i18nKey: "code_list.ComponentType.table"},
    {value: "tableColumn", label: "表列", i18nKey: "code_list.ComponentType.tableColumn"},
    {value: "list", label: "表格", i18nKey: "code_list.ComponentType.list"},
    {value: "listCard", label: "表格", i18nKey: "code_list.ComponentType.listCard"},
    {value: "imageShow", label: "显示图片", i18nKey: "code_list.ComponentType.imageShow"},
    {value: "fileLink", label: "文件链接", i18nKey: "code_list.ComponentType.fileLink"},
    {value: "url", label: "地址链接", i18nKey: "code_list.ComponentType.url"},
    {value: "aggregate", label: "数据聚合", i18nKey: "code_list.ComponentType.aggregate"},
  ],
  AggregateType: [
    {value: "sum", label: "求和", i18nKey: "code_list.AggregateType.sum"},
    {value: "max", label: "最大值", i18nKey: "code_list.AggregateType.max"},
    {value: "min", label: "最小值", i18nKey: "code_list.AggregateType.min"},
    {value: "avg", label: "平均值", i18nKey: "code_list.AggregateType.avg"},
    {value: "count", label: "计数", i18nKey: "code_list.AggregateType.count"},
  ],
  UserDocumentType: [{value: "", label: "请选择", i18nKey: "code_list.common.empty"},
    {value: "rfp", label: "需求请求", i18nKey: "code_list.UserDocumentType.rfp"},
    {value: "email", label: "邮件", i18nKey: "code_list.UserDocumentType.email"},
    {value: "meeting_transcript", label: "会议转录", i18nKey: "code_list.UserDocumentType.meeting_transcript"},
    {value: "meeting_minutes", label: "会议纪要", i18nKey: "code_list.UserDocumentType.meeting_minutes"},
    {value: "recording", label: "现场录音", i18nKey: "code_list.UserDocumentType.recording"},
  ],
  RequirementType: [{value: "", label: "请选择", i18nKey: "code_list.common.empty"},
    {value: "create_function_list", label: "创建功能列表", i18nKey: "code_list.RequirementType.create_function_list"},
    {
      value: "create_function_demand",
      label: "创建功能详细需求",
      i18nKey: "code_list.RequirementType.create_function_demand"
    },
    {value: "create_biz_flow", label: "创建流程图", i18nKey: "code_list.RequirementType.create_biz_flow"},
    {value: "create_page_flow", label: "创建页面流", i18nKey: "code_list.RequirementType.create_page_flow"},
    {value: "create_page_demand", label: "创建页面需求", i18nKey: "code_list.RequirementType.create_page_demand"},
    {value: "create_api_demand", label: "创建接口需求", i18nKey: "code_list.RequirementType.create_api_demand"},
    {value: "update_page_demand", label: "更新页面需求", i18nKey: "code_list.RequirementType.update_page_demand"},
    {value: "update_api_demand", label: "更新接口需求", i18nKey: "code_list.RequirementType.update_api_demand"},
  ],
  ApiCreateType: [
    {value: "crud", label: "标准接口", i18nKey: "code_list.ApiCreateType.crud"},
    {value: "custom", label: "自定义", i18nKey: "code_list.ApiCreateType.custom"},
  ],
  RequirementPieceType: [{value: "", label: "请选择", i18nKey: "code_list.common.empty"},
    {value: "page_description", label: "页面说明", i18nKey: "code_list.RequirementPieceType.page_description"},
    {value: "api_description", label: "接口说明", i18nKey: "code_list.RequirementPieceType.api_description"},
    {
      value: "biz_flow_description",
      label: "业务流程说明",
      i18nKey: "code_list.RequirementPieceType.biz_flow_description"
    },
    {
      value: "page_flow_description",
      label: "页面流说明",
      i18nKey: "code_list.RequirementPieceType.page_flow_description"
    },
    {value: "api_input_fields", label: "接口入参字段定义", i18nKey: "code_list.RequirementPieceType.api_input_fields"},
    {value: "update_api", label: "接口出参字段定义", i18nKey: "code_list.RequirementPieceType.update_api"},
    {
      value: "page_search_fields",
      label: "页面查询条件字段",
      i18nKey: "code_list.RequirementPieceType.page_search_fields"
    },
    {
      value: "search_result_fields",
      label: "页面查询结果字段",
      i18nKey: "code_list.RequirementPieceType.search_result_fields"
    },
  ],
  PromptResultType: [{value: "", label: "请选择", i18nKey: "code_list.common.empty"},
    {value: "json", label: "格式化数据JSON", i18nKey: "code_list.PromptResultType.json"},
    {value: "python_code", label: "Python源代码", i18nKey: "code_list.PromptResultType.python_code"},
    {value: "text", label: "纯文本内容", i18nKey: "code_list.PromptResultType.text"},
    {value: "picture", label: "图片", i18nKey: "code_list.PromptResultType.picture"},
  ],
  PageSectionType: [
    {value: "", label: "请选择", i18nKey: "code_list.common.empty"},
    {value: "condition", label: "查询条件", i18nKey: "code_list.PageSectionType.condition"},
    {value: "input", label: "数据输入", i18nKey: "code_list.PageSectionType.input"},
    {value: "detail", label: "数据显示", i18nKey: "code_list.PageSectionType.detail"},
    {value: "search_result", label: "检索结果数据表", i18nKey: "code_list.PageSectionType.search_result"},
    {value: "table", label: "数据表格", i18nKey: "code_list.PageSectionType.table"},
    {value: "list", label: "数据列表", i18nKey: "code_list.PageSectionType.list"},
    {value: "container", label: "区块容器", i18nKey: "code_list.PageSectionType.container"},
    {value: "button", label: "按钮工具条", i18nKey: "code_list.PageSectionType.button"},
    {value: "statistics", label: "统计数据", i18nKey: "code_list.PageSectionType.statistics"},
    {value: "chart", label: "数据图表", i18nKey: "code_list.PageSectionType.chart"},
    {value: "map", label: "地图", i18nKey: "code_list.PageSectionType.map"},
    {value: "tree", label: "树状图", i18nKey: "code_list.PageSectionType.tree"},
    {value: "chart_line", label: "折线图", i18nKey: "code_list.PageSectionType.chart_line"},
    {value: "chart_pie", label: "饼状图", i18nKey: "code_list.PageSectionType.chart_pie"},
    {value: "chart_bar", label: "柱状图", i18nKey: "code_list.PageSectionType.chart_bar"},
  ],
  PageLayoutSectionType: [{value: "", label: "请选择", i18nKey: "code_list.common.empty"},
    {value: "condition", label: "查询条件", i18nKey: "code_list.PageLayoutSectionType.condition"},
    {value: "input", label: "数据输入", i18nKey: "code_list.PageLayoutSectionType.input"},
    {value: "detail", label: "数据显示", i18nKey: "code_list.PageLayoutSectionType.detail"},
    {value: "search_result", label: "检索结果数据表", i18nKey: "code_list.PageLayoutSectionType.search_result"},
    {value: "button", label: "按钮工具条", i18nKey: "code_list.PageLayoutSectionType.button"},
  ],
  FileType: [{value: "", label: "请选择", i18nKey: "code_list.common.empty"},
    {value: "picture", label: "图片", i18nKey: "code_list.FileType.picture"},
    {value: "html", label: "HTML", i18nKey: "code_list.FileType.html"},
    {value: "zip", label: "图片", i18nKey: "code_list.FileType.zip"},
    {value: "jpg", label: "图片", i18nKey: "code_list.FileType.picture"},
    {value: "jpeg", label: "图片", i18nKey: "code_list.FileType.picture"},
    {value: "png", label: "图片", i18nKey: "code_list.FileType.picture"},
  ],
  PrototypeDocumentType: [{value: "", label: "请选择", i18nKey: "code_list.common.empty"},
    {value: "picture", label: "图片", i18nKey: "code_list.PrototypeDocumentType.picture"},
    {value: "html", label: "HTML", i18nKey: "code_list.PrototypeDocumentType.html"},
    {value: "zip", label: "HTML", i18nKey: "code_list.PrototypeDocumentType.html"},
    {value: "ZIP", label: "HTML", i18nKey: "code_list.PrototypeDocumentType.html"},
    {value: "jpg", label: "图片", i18nKey: "code_list.PrototypeDocumentType.picture"},
    {value: "jpeg", label: "图片", i18nKey: "code_list.PrototypeDocumentType.picture"},
    {value: "png", label: "图片", i18nKey: "code_list.PrototypeDocumentType.picture"},
  ],
  PrototypeDocumentFileType: [{value: "", label: "请选择", i18nKey: "code_list.common.empty"},
    {value: "picture", label: "图片", i18nKey: "code_list.PrototypeDocumentFileType.picture"},
    {value: "html", label: "HTML", i18nKey: "code_list.PrototypeDocumentFileType.html"},
  ],
  PrototypeType: [{value: "", label: "请选择", i18nKey: "code_list.common.empty"},
    {value: "project", label: "图片", i18nKey: "code_list.PrototypeType.project"},
    {value: "module", label: "HTML", i18nKey: "code_list.PrototypeType.module"},
    {value: "function", label: "HTML", i18nKey: "code_list.PrototypeType.function"},
  ],

  PageCommandType: [{value: "", label: "请选择", i18nKey: "code_list.common.empty"},
    {value: "component", label: "component", i18nKey: "code_list.PageCommandType.component"},
    {value: "page", label: "page", i18nKey: "code_list.PageCommandType.page"},
  ],
  WorkingLanguage: [
    {value: "cn_zh", label: "中文", i18nKey: "code_list.WorkingLanguage.cn_zh"},
    {value: "ja_jp", label: "日文", i18nKey: "code_list.WorkingLanguage.ja_jp"},
    {value: "en_us", label: "英文", i18nKey: "code_list.WorkingLanguage.en_us"},
  ],
  WorkTaskType: [
    {value: "page", label: "页面", i18nKey: "code_list.WorkTaskType.page"},
    {value: "internal_api", label: "内部接口", i18nKey: "code_list.WorkTaskType.internal_api"},
    {value: "external_api", label: "外部接口", i18nKey: "code_list.WorkTaskType.external_api"},
    {value: "cron_task", label: "定时任务", i18nKey: "code_list.WorkTaskType.cron_task"},
    {value: "report", label: "报表", i18nKey: "code_list.WorkTaskType.report"},
  ],
  SearchType: [
    {value: "value", label: "相等匹配", i18nKey: "code_list.SearchType.value"},
    {value: "keyword", label: "模糊关键词", i18nKey: "code_list.SearchType.keyword"},
    {value: "range", label: "范围", i18nKey: "code_list.SearchType.range"},
  ],
  PageLayoutTemplateType: [
    {
      value: "react+antd+recharts",
      label: "react+antd+recharts",
      i18nKey: "code_list.PageLayoutTemplateType.react+antd+recharts"
    },
    {
      value: "react+antd+echarts",
      label: "react+antd+echarts",
      i18nKey: "code_list.PageLayoutTemplateType.react+antd+echarts"
    },
    {
      value: "react+antd+chartjs",
      label: "react+antd+chartjs",
      i18nKey: "code_list.PageLayoutTemplateType.react+antd+chartjs"
    },
    {
      value: "react+mui+recharts",
      label: "react+mui+recharts",
      i18nKey: "code_list.PageLayoutTemplateType.react+mui+recharts"
    },
    {value: "vue+echarts", label: "vue+echarts", i18nKey: "code_list.PageLayoutTemplateType.vue+echarts"},
  ],
  SourceGenerateType: [
    {value: "llm", label: "大模型生成", i18nKey: "code_list.SourceGenerateType.llm"},
    {value: "template", label: "模版生成", i18nKey: "code_list.SourceGenerateType.template"},
  ],
  EntityType: [
    {value: "dimension", label: "维表", i18nKey: "code_list.EntityType.dimension"},
    {value: "fact", label: "事实表", i18nKey: "code_list.EntityType.fact"},
    {value: "summary", label: "汇总表", i18nKey: "code_list.EntityType.summary"},
  ],

}
codeList.ApiType = codeList.InternalApiType.concat(codeList.ExternalApiType)
